sudo: required
dist: trusty

language: haxe

haxe:
 - "3.4.7"
 - "development"
 
hxml:
- test/ImportAll.hxml

install:
 - haxelib install test/ImportAll.hxml
 - haxelib dev AmqpExterns .
 
script:
- haxe test/ImportAll.hxml
 
deploy:
 - provider: script
   haxe: 3.4.7
   script: bash ./release_haxelib.sh $HAXELIB_PWD